### ISSUE TITLE
Indicator position customization

### ISSUE THREAD

**Issue by LeeWeeder** [ehsannarmani/ComposeCharts#11]
### Introduction
Good day!

I stumbled upon this repo while looking for a line chart library for my app. And well, I'm impressed with how easy it was to implement the API. It is clear and straightforward. I want to thank you first before my real issue. Thank you!

### Issue: Feature request
With all that customization, a custom **indicator placement** would be best. On the use case of my app, I want to position the indicator to the end, instead of at the start.

PS. I already have the implementation of the feature for line and column charts and would like to ask if contributions to your project are allowed 'cause I want to create a pull request.

Sample from my implementation

![compose_chart](https://github.com/ehsannarmani/ComposeCharts/assets/113887292/f1cb35c6-f37e-4014-85f0-84b465672751)

**Comment by ehsannarmani** [comment]
@LeeWeeder Hi dear.
Thank you so much for your lovely and motivating comment.
I glad to hear that the library is useful for you.
Definitely yes, you can create your pull request, but the small issue on your implementation is that alignment of indicators text
If you make that indicators text alignment left to right it will better.

**Comment by LeeWeeder** [comment]
> Definitely yes, you can create your pull request...

Thank you! 
> but the small issue on your implementation is that alignment of indicators text If you make that indicators text alignment left to right it will better.

To clarify if I understand your suggestion correctly, does the below image achieve your wanted results?
![image](https://github.com/ehsannarmani/ComposeCharts/assets/113887292/7e194c77-b7c8-4f8c-9186-79649a2e0d11)

**Comment by ehsannarmani** [comment]
> To clarify if I understand your suggestion correctly, does the below image achieve your wanted results?

Yeah exactly, thank you so much.
