### ISSUE TITLE
Popup problem

### ISSUE THREAD

**Issue by BabakR-alefba** [ehsannarmani/ComposeCharts#13]
Hello. 
How can I prevent to show the popup between two point? 
I want to show the popup when user touch only the dots. 
![image](https://github.com/ehsannarmani/ComposeCharts/assets/124586737/7c784b33-082d-4a99-a4ca-f70ca21eceb1)

Another problem. As you can see in above pic I want to add some dots between the labels. I thinks the chart can't support this feature right now. Am I right?

**Comment by ehsannarmani** [comment]
Hi @BabakR-alefba 
The line chart currently developed for showing statistic data for example weather of a city, in this sample user can see the temperature in between 2 days with that popup, so currently, there is no feature to just visible popup in specific situation, but ill make a plan to do that.

But about adding dots between the labels, i didnt understand that, give more information about that.

**Comment by BabakR-alefba** [comment]
I mean something like this: https://www.highcharts.com/demo/android/spline-irregular-time
