### ISSUE TITLE
The problem when there is a lot of data 

### ISSUE THREAD

**Issue by mrihsann** [ehsannarmani/ComposeCharts#15]
When there is too much data, distortion occurs in the graph. As the data increases, scrolling like LazyRow logic would be great.

![image](https://github.com/user-attachments/assets/f946b999-139e-48ec-a61f-3f8d06620bae)

**Comment by ehsannarmani** [comment]
Hi @mrihsann , currently we have no scrolling feature. to work correctly, you should decresae bar width.
