### ISSUE TITLE
Label Rotation not working

### ISSUE THREAD

**Issue by itsmeRonjie** [ehsannarmani/ComposeCharts#19]
![image](https://github.com/user-attachments/assets/07152430-37be-4bf3-8e80-f96f3de971c9)
![image](https://github.com/user-attachments/assets/46e3b14a-dda9-4da0-a962-52a7f3855647)

how to change label angle??

**Comment by ehsannarmani** [comment]
Hi, currently rotation It applied only when there is a label whose width is more than 50% different from the others, but in the next versions ill put a parameter to force rotate labels.

**Comment by ehsannarmani** [comment]
@itsmeRonjie Hi dear, its available in 0.0.14 version now.

**Comment by itsmeRonjie** [comment]
@ehsannarmani Thank you. it works on bar chart but not in Line charts. Can you try?
