### ISSUE TITLE
y Axis label color for Dark Theme?

### ISSUE THREAD

**Issue by mikelantzelo** [ehsannarmani/ComposeCharts#24]

**Comment by mikelantzelo** [comment]
Is it possible to change the yaxis labels color?

**Comment by ehsannarmani** [comment]
Hi @mikelantzelo , you can pass text style to label properties in all of charts.
![image](https://github.com/user-attachments/assets/d76dd33d-dbdd-4cb1-8a44-e402f3e907f9)

**Comment by mikelantzelo** [comment]
@ehsannarmani. Hi and thanks for this great library. This aproach only changes the labels color on xAxis. As show in picture
![Στιγμιότυπο οθόνης 2024-09-21 095745](https://github.com/user-attachments/assets/9bda711d-7232-4d9f-89b5-e3f6fa408530)

**Comment by ehsannarmani** [comment]
@mikelantzelo i glad to hear it library is usefull for you.
You can set text style in indicator properties to change that x axis labels style.

![image](https://github.com/user-attachments/assets/3d5463d3-9ecf-4fad-8ef0-ce9cd316dc4e)

**Comment by mikelantzelo** [comment]
@ehsannarmani That's great!!! Thank you!!!
