### ISSUE TITLE
Plot Bars in between x positions

### ISSUE THREAD

**Issue by marcusfreitas** [ehsannarmani/ComposeCharts#27]
Hey, I'm using your library and its really amazing, but I need to draw the bars in between values just like this image here:

![Screenshot 2024-09-25 at 16 02 20](https://github.com/user-attachments/assets/05b4dcb3-021c-4fb9-a593-1bd420a33d40)

you see that the bars are in-between values like the 35 and 40 there

I was trying to do something similar with your library but the problem is that is not consistent, I'm using the spacing parameter on the BarProperties, but the position is not consistent as the graph is drawn the bars changes the position some times is in between and other times is on top of the value.

Is it feasible? Is their a way to do something like the image above?

**Comment by marcusfreitas** [comment]
I jus figured out that what I need is somewhat a different kind of graph, its called histogram, its almost identical to the bar graph but the differences are the intervals on the x-axis and the bars the covers that interval

**Comment by ehsannarmani** [comment]
Hi @marcusfreitas , currently we have not this feature in library.
