### ISSUE TITLE
Format Number at Y-Axis

### ISSUE THREAD

**Issue by dibyendu-mahata** [ehsannarmani/ComposeCharts#28]
Instead of showing 5000, let's consider 5,000.

**Comment by ehsannarmani** [comment]
Hi @dibyendu-mahata , can you explain your problem with a picture?

**Comment by dibyendu-mahata** [comment]
It's not really a problem, but a UI improvement.
At the y-axis we have numbers, when the number is greater than 4 digits, let's format it.
So instead of showing 58965, we can format it with a comma, like this: 58,965.

1234 -> 1,234
75236 -> 75,236
587412 -> 587,412

**Comment by ehsannarmani** [comment]
If i understand your meaning, we have contentBuilder in IndicatorProperties, so you can show the indicators as you wish:
indicatorProperties = IndicatorProperties(contentBuilder = { DecimalFormat("#,###").format(it) } )

**Comment by dibyendu-mahata** [comment]
Yeah!
Thank you ✨
