### ISSUE TITLE
Bar click

### ISSUE THREAD

**Issue by marcusfreitas** [ehsannarmani/ComposeCharts#3]
Hey its there a way to have a Bar selected listener? When the user taps on the bar or do a long press I'd like to trigger some stuff in my app.... is there a way to do that? I can see that the PieChart has a onPieClick but the ColumnChart doesn't have this parameter

**Comment by ehsannarmani** [comment]
@marcusfreitas  Hi dear, not yet, but ill add that parameter for row and column charts soon.

**Comment by ehsannarmani** [comment]
@marcusfreitas tap gestures added in 0.0.5
