### ISSUE TITLE
Custom dot or bar value labels.

### ISSUE THREAD

**Issue by waqar-ahmed** [ehsannarmani/ComposeCharts#30]
Hi, currently the displayed value for the bar or dot on the graph is the plotted value. The only way to customize this at the moment is by using **ContentBuilder**, which simply adds a suffix to the value:
![image](https://github.com/user-attachments/assets/ebccf006-85b2-4f31-a969-d013fcfd3ecc)

I want to specify custom labels for dots or bars. For example, if I'm plotting time in minutes or hours, I’d like to display the labels as **2 hrs 5 mins** instead of **125.0**. Is there any way to achieve this customization?

Thank you.

**Comment by ehsannarmani** [comment]
Hi @waqar-ahmed , whats your data list type? are you using minute values for chart data?

**Comment by waqar-ahmed** [comment]
> Hi @waqar-ahmed , whats your data list type? are you using minute values for chart data?

Hi, thank you for reply. Since, I can only pass double values, I am passing in minutes as data list. But 120 mins is not so understandable compared to 2 hrs.

**Comment by ehsannarmani** [comment]
@waqar-ahmed , that content builder gives you the value, you can convert that to time, for example in your case, the given value in content builder function is minutes, you should convert minutes to readable time.
