### ISSUE TITLE
Can I hide the legend (label and dot) of the chart? 

### ISSUE THREAD

**Issue by chriszal** [ehsannarmani/ComposeCharts#31]
Im not sure if I missed anything but I don't seem to be able to hide the legend of the whole chart. So the dot and the label. I can Just make the label be empty but then I don't know how to hide the dot that shows the colour of the line. I'm using a line chart by the way.

**Comment by ehsannarmani** [comment]
@chriszal hi dude. please explain what do you need with a picture, i did not understand what you mean exactly.

**Comment by chriszal** [comment]
I wanted my chart to look like this so basically not have the label ontop with the colored dot in front of it. 
![Screenshot_2024-10-08-13-59-22-26_d79f27bf609fd8e25af1ee25ad7635ab](https://github.com/user-attachments/assets/c7e7790a-c97f-434b-af3f-6569f29d8e52)

**Comment by ehsannarmani** [comment]
![image](https://github.com/user-attachments/assets/ab026d37-49f4-4a33-a1a4-238ecda26aef)
we have a chart like that in sample, read the sample and you can implement this according to sample

**Comment by JustKhit** [comment]
@chriszal I'm not sure if this you were looking for:

try adding to the chart
`labelHelperProperties = LabelHelperProperties(
    enabled = false
)`
