### ISSUE TITLE
Support step-based indicator labels

### ISSUE THREAD

**Issue by Queatz** [ehsannarmani/ComposeCharts#39]
Currently, we can only specify the number of indicator labels. We should also be able to specify a step (or specify individually). For example, we might want to step be 10 units, and don't mind how many indicators there are.

**Comment by ehsannarmani** [comment]
Hi @Queatz , you can calculate for your self to do that, divide your max value to 10 to do that.

**Comment by ehsannarmani** [comment]
Now, in 0.0.15 version you can use step based indicators
