### ISSUE TITLE
popup prevents the ability to scroll the screen

### ISSUE THREAD

**Issue by danyloplaksyvy** [ehsannarmani/ComposeCharts#47]
Hello, i have an issue

When I try to scroll the screen, but I accidentally tap on the LineChart, it can't scroll because of the popup. I set popUpProperties(enabled = false), but i still have that problem. How can I fix it? 

@Composable
fun HomeChartBox(companyViewModel: CompanyViewModel, chartData: List<Double>, selectedIndex: Int) {
    val mainStat by companyViewModel.mainStat.observeAsState()

    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.customColorsPalette.homeStatCard),
        elevation = CardDefaults.elevatedCardElevation(12.dp),
        shape = RoundedCornerShape(16.dp),
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 16.dp)
    ) {
        Column(
            modifier = Modifier
                .padding(16.dp)
                .fillMaxWidth()
                .height(256.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Top
        ) {
            Text(
                text = if (selectedIndex == 0) "Виторг" else "Прибуток",
                maxLines = 1,
                color = MaterialTheme.colorScheme.onBackground.copy(0.8f),
            )
            Text(
                text = if (selectedIndex == 0) "${mainStat?.data?.earnings?.roundToTwoDecimals() ?: 0.00} ₴" else "${mainStat?.data?.profit?.roundToTwoDecimals() ?: 0.00} ₴",
                maxLines = 1,
                color = MaterialTheme.colorScheme.onBackground,
                style = MaterialTheme.typography.titleLarge,
                modifier = Modifier.padding(bottom = 8.dp)
            )
            LineChart(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(200.dp)
                    .padding(horizontal = 8.dp),
                popupProperties = PopupProperties(enabled = false),
                indicatorProperties = HorizontalIndicatorProperties(
                    textStyle = MaterialTheme.typography.bodyMedium.copy(
                        color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.8f)
                    ),
                    padding = 8.dp,
                ),
                labelHelperProperties = LabelHelperProperties(enabled = false),
                gridProperties = GridProperties(enabled = false),
                data = listOf(
                    Line(
                        popupProperties = PopupProperties(enabled = false),
                        label = "",
                        values = chartData,
                        color = SolidColor(MaterialTheme.customColorsPalette.chartColor),
                        firstGradientFillColor = MaterialTheme.customColorsPalette.chartColor.copy(
                            alpha = .4f
                        ),
                        secondGradientFillColor = Color.Transparent,
                        strokeAnimationSpec = tween(2000, easing = EaseInOutCubic),
                        gradientAnimationDelay = 1000,
                        drawStyle = DrawStyle.Stroke(width = 1.dp),
                    )
                ),
                animationMode = AnimationMode.Together(delayBuilder = { it * 500L }),
            )
        }
    }
}

**Comment by ehsannarmani** [comment]
Hi @danyloplaksyvy , thank you for reporting the problem.
please upgrade the library version to 0.0.17 and test that, let me know if the issue still exist. ( in this version you can use popup in scrollable parent, it should be ok and it should not prevent vertical scrolling )
