### ISSUE TITLE
Does ComposeCharts supoort to show the live data in the chart?

### ISSUE THREAD

**Issue by Zhao-Michael** [ehsannarmani/ComposeCharts#48]
I'd like to implement the system cpu/memory chart with live data. 

How to implement it with Flow ?

Thanks in advance~

I try these codes, but It doesn't update automatically:

View:

                Column {
                    val axisProperties = GridProperties.AxisProperties(
                        enabled = true,
                        style = StrokeStyle.Dashed(intervals = floatArrayOf(10f, 10f)),
                        color = SolidColor(Color.Gray),
                        thickness = (.5).dp,
                        lineCount = 10
                    )

                    val gridProperties = GridProperties(
                        enabled = true,
                        xAxisProperties = axisProperties,
                        yAxisProperties = axisProperties
                    )

                    val numbers = deviceViewModel.numbers.collectAsStateWithLifecycle().value

                    LineChart(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(150.dp)
                            .padding(horizontal = 12.dp),
                        data = remember {
                            listOf(
                                Line(
                                    label = "CPU",
                                    values = numbers,
                                    color = SolidColor(Color(0xFF23af92)),
                                    firstGradientFillColor = Color(0xFF2BC0A1).copy(alpha = .5f),
                                    secondGradientFillColor = Color.Transparent,
                                    strokeAnimationSpec = tween(400, easing = EaseInOutCubic),
                                    gradientAnimationDelay = 300,
                                    drawStyle = DrawStyle.Stroke(width = 2.dp),
                                )
                            )
                        },
                        animationMode = AnimationMode.Together(delayBuilder = {
                            it * 300L
                        }),
                        gridProperties = gridProperties,
                        minValue = 0.0,
                        maxValue = 100.0
                    )
                }

DeviceViewModel:

    var counter = 0
    private val _numbers = MutableStateFlow<List<Double>>(emptyList())
    val numbers: StateFlow<List<Double>> = _numbers.asStateFlow()

    viewModelScope.launch {
            doubleFlow()
                .onEach { number ->
                    _numbers.value += number.toDouble()
                }
                .launchIn(viewModelScope)
    }

    fun doubleFlow() = flow {
        while (true) {
            counter++
            emit(counter)
            delay(1000)
        }
    }

**Comment by ehsannarmani** [comment]
hi @Zhao-Michael , in the remember parameters, put your data and test it:
data = remember(data){
 ...
}

**Comment by Zhao-Michael** [comment]
@ehsannarmani thanks a lot, It works, But the line line kept flickering, how to disable the animation?

**Comment by Zhao-Michael** [comment]
animationDelay = 0
