### ISSUE TITLE
Cannot Override labels in Bar Chart

### ISSUE THREAD

**Issue by itsmeRonjie** [ehsannarmani/ComposeCharts#52]

**Comment by ehsannarmani** [comment]
Hi @itsmeRonjie , please explain your exact problem.

**Comment by itsmeRonjie** [comment]
Column Chart overriding label doesn't work unlike in Line Chart

This is my labelProperties in ColumnChart (not working)
<img width="645" alt="Screenshot 2024-12-02 at 8 57 08 AM" src="https://github.com/user-attachments/assets/d3dea99d-7dab-4d34-9a32-5920758657c1">

This is my labelProperties in LineChart (working)
<img width="648" alt="Screenshot 2024-12-02 at 8 57 57 AM" src="https://github.com/user-attachments/assets/143c5225-b447-4b53-9e8c-b819a1001e04">

**Comment by ehsannarmani** [comment]
Hi @itsmeRonjie , labels parameter in label properties is just working on line charts currently, because the number of labels may be different from the number of data.
In the bar charts you can define labels in data, no need to use like this.

**Comment by ehsannarmani** [comment]
in the next updates, might change this scenario and implement a feature to override labels with this parameter.

**Comment by ehsannarmani** [comment]
Hi @itsmeRonjie , in the `0.1.0` version, you can override all of charts labels with labels property in label properties.
Thank you for sharing your problem and helping to improve the library.
