### ISSUE TITLE
How to dynamically change the font color of LabelProperties

### ISSUE THREAD

**Issue by Lans** [ehsannarmani/ComposeCharts#53]
I used the onBarClick method, but how do I change the font color at the bottom of the corresponding bar chart after clicking?

**Comment by ehsannarmani** [comment]
Hi @Lans , if you want to set specific text style for every label, it's not supported currently.

**Comment by Lans** [comment]
![image](https://github.com/user-attachments/assets/65069999-98f5-406a-ba82-b9eebd566e15)
I want to achieve this effect, and I hope to support it in the future

**Comment by ehsannarmani** [comment]
Thank you for your suggestion, in the next versions i will add a feature to do this.

**Comment by ehsannarmani** [comment]
Hi @Lans , in the `0.1.0` version you can build your own component for labels, now i think you should be able to do this job with this feature.
