### ISSUE TITLE
Chart Labels Not Visible in Dark Theme

### ISSUE THREAD

**Issue by 0xJihan** [ehsannarmani/ComposeCharts#61]
When switching to the dark theme, the labels, text, and other elements in the chart are not visible. It seems like a hardcoded black color is being used for the text, which makes it blend into the dark background.

![bug](https://github.com/user-attachments/assets/d228279b-0ec7-41fb-9a74-0fb5e75f51de)

@yashwanthgajji 
![light](https://github.com/user-attachments/assets/52232722-9d1e-48fb-8bd5-1d6f140479ec)

**Comment by ehsannarmani** [comment]
hi @0xJihan , you can set style for labels, please read [document](https://ehsannarmani.github.io/ComposeCharts/chart-properties/labels/)
