### ISSUE TITLE
Shows wrong number on tooltip

### ISSUE THREAD

**Issue by EMIN3M1986** [ehsannarmani/ComposeCharts#7]
Hello. Thanks for the good library. 
I have a problem with tooltip on the chart.
For example I pass the number 242747.0, but when I navigate on the chart the tooltip show the number 254473.8620101015.

**Comment by ehsannarmani** [comment]
@EMIN3M1986 Hi dear, can i see your code?

**Comment by EMIN3M1986** [comment]
Sorry. This is not mine. I am not the owner. I do not have access to add you in repository

**Comment by ehsannarmani** [comment]
Ok ill check it.

**Comment by ehsannarmani** [comment]
@EMIN3M1986 It has become more accurate in 0.0.8

**Comment by EMIN3M1986** [comment]
Thanks.
