### ISSUE TITLE
xAxis problem

### ISSUE THREAD

**Issue by BabakR-alefba** [ehsannarmani/ComposeCharts#9]
Hi. I set "xAxisProperties" -> lineCount = 4  like below image:
![Screenshot_1719717909](https://github.com/ehsannarmani/ComposeCharts/assets/124586737/531cad66-94cb-4dae-ab92-bda5edc7235d)

but some times it got problem. like below: 
![Screenshot_1719717900](https://github.com/ehsannarmani/ComposeCharts/assets/124586737/3b5a3d21-bdc5-4fa0-817c-7ec313b5ccad)
as you see the number "37" repeat two times.

**Comment by ehsannarmani** [comment]
@BabakR-alefba hi dear, please mention your max value & min value

Notice that count property in IndicatorProperties specifies the count of that numbers which positioned in left of your chart, the xAxisLineCount is just the count of lines.

**Comment by ehsannarmani** [comment]
@BabakR-alefba The problem fixed in [0.0.9](https://github.com/ehsannarmani/ComposeCharts/tree/0.0.9)
